# Generated by Django 4.1.3 on 2022-12-12 14:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fishingbs.accounts.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_type', models.CharField(choices=[('сафрид', 'Сафрид'), ('чернокоп', 'Чернокоп'), ('паламуд', 'Паламуд'), ('лефер', 'Лефер'), ('попче', 'Попче'), ('зарган', 'Зарган')], max_length=8)),
                ('location', models.CharField(choices=[('atiya', 'Атия'), ('diuni', 'Дюни'), ('elenite', 'Елените'), ('emine', 'Емине'), ('kanala', 'Канала'), ('koketrais', 'Кокетрайс'), ('maslen-nos', 'Маслен'), ('megalkata', 'Мегалката'), ('pomorie', 'Поморие'), ('ravda', 'Равда'), ('sozopol', 'Созопол'), ('stavrova-banka', 'Ставрова банка'), ('talasakra', 'Таласакра'), ('chukalqta', 'Чукалята')], max_length=14)),
                ('intensity', models.CharField(choices=[('low', 'Малък'), ('medium', 'Среден'), ('high', 'Голям')], max_length=6)),
                ('last_most_intense', models.TimeField(default=datetime.datetime.now)),
                ('type_of_catching', models.CharField(choices=[('trolling', 'Тролинг'), ('chipare', 'Чипаре')], default=1, max_length=8)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='catches/', validators=[fishingbs.accounts.validators.image_max_size_validator])),
                ('from_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
