# Generated by Django 4.1.3 on 2022-12-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giveinformationmodel',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='giveinformationmodel',
            name='fish_type',
            field=models.CharField(choices=[('Сафрид', 'Сафрид'), ('Чернокоп', 'Чернокоп'), ('Паламуд', 'Паламуд'), ('Лефер', 'Лефер'), ('Попче', 'Попче'), ('Зарган', 'Зарган')], max_length=8),
        ),
        migrations.AlterField(
            model_name='giveinformationmodel',
            name='intensity',
            field=models.CharField(choices=[('Малка', 'Малка'), ('Средна', 'Средна'), ('Голяма', 'Голяма')], max_length=6),
        ),
        migrations.AlterField(
            model_name='giveinformationmodel',
            name='location',
            field=models.CharField(choices=[('atiya', 'Атия'), ('diuni', 'Дюни'), ('elenite', 'Елените'), ('emine', 'Емине'), ('kanala', 'Канала'), ('koketrais', 'Кокетрайс'), ('maslen-nos', 'Маслен нос'), ('megalkata', 'Мегалката'), ('pomorie', 'Поморие'), ('ravda', 'Равда'), ('sozopol', 'Созопол'), ('stavrova-banka', 'Ставрова банка'), ('talasakra', 'Таласакра'), ('chukalqta', 'Чукалята')], max_length=14),
        ),
        migrations.AlterField(
            model_name='giveinformationmodel',
            name='type_of_catching',
            field=models.CharField(choices=[('Тролинг', 'Тролинг'), ('Чипаре', 'Чипаре')], max_length=7),
        ),
    ]
