version: '3.4'

services:
  web:
    build: ./fishingbs
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./fishingbs/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./fishingbs/fishingbs/.env
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 135790
      POSTGRES_USER: lasabito
      POSTGRES_DB: fishingbs_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
