version: '3.4'

services:
  web:
    image: lasabito/fishingbs
    build: ./fishingbs
    command: gunicorn fishingbs.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./staticfiles:/tmp/fishingbs/staticfiles
    ports:
      - 8000:8000
    env_file:
      - ./fishingbs/fishingbs/.env.prod
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 135790
      POSTGRES_USER: lasabito
      POSTGRES_DB: fishingbs_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./staticfiles:/home/app/web/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web
