# Generated by Django 4.1.3 on 2022-12-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseTownModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(choices=[('sozopol', 'Созопол'), ('черноморец', 'Черноморец'), ('атия', 'Атия'), ('бургас', 'Бургас'), ('поморие', 'Поморие'), ('равда', 'Равда'), ('несебър', 'Несебър'), ('емона ', 'Емона')], max_length=15)),
            ],
        ),
    ]
