# Generated by Django 4.1.3 on 2022-12-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choosetownmodel',
            name='town',
            field=models.CharField(choices=[('sozopol', 'Созопол'), ('chernomorec', 'Черноморец'), ('atiya', 'Атия'), ('burgas', 'Бургас'), ('pomorie', 'Поморие'), ('ravda', 'Равда'), ('nesebar', 'Несебър'), ('emona', 'Емона')], max_length=15),
        ),
    ]
