# Generated by Django 4.1.3 on 2022-12-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_choosetownmodel_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choosetownmodel',
            name='town',
            field=models.CharField(choices=[('atiya', 'Атия'), ('burgas', 'Бургас'), ('emona', 'Емона'), ('nesebar', 'Несебър'), ('pomorie', 'Поморие'), ('ravda', 'Равда'), ('sozopol', 'Созопол'), ('chernomorets', 'Черноморец')], max_length=15),
        ),
    ]
