# Generated by Django 4.1.3 on 2022-12-05 17:29

from django.db import migrations, models
import fishingbs.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_id_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[fishingbs.accounts.validators.image_max_size_validator]),
        ),
    ]
