# Generated by Django 4.1.3 on 2022-12-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_appuser_first_logged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_logged',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
