# Generated by Django 4.1.3 on 2022-12-14 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeathersWarningModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Бургаски залив', max_length=20)),
                ('warning_type', models.CharField(choices=[('Силно вълнение', 'Силно вълнение'), ('Буря', 'Буря'), ('Друго', 'Друго')], max_length=14)),
                ('comment', models.TextField(max_length=300)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
