# Generated by Django 4.1.3 on 2022-12-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_warnings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeathersWarningModel',
            new_name='WeatherWarningsModel',
        ),
    ]
