# Generated by Django 4.1.3 on 2022-12-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_warnings', '0003_weatherwarningsmodel_from_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherwarningsmodel',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
