# Generated by Django 4.1.3 on 2022-12-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchinfishingareamodel',
            name='location',
            field=models.CharField(choices=[('atiya', 'Атия'), ('diuni', 'Дюни'), ('elenite', 'Елените'), ('emine', 'Емине'), ('kanala', 'Канала'), ('koketrais', 'Кокетрайс'), ('maslen-nos', 'Маслен нос'), ('megalkata', 'Мегалката'), ('pomorie', 'Поморие'), ('ravda', 'Равда'), ('sozopol', 'Созопол'), ('stavrova-banka', 'Ставрова банка'), ('talasakra', 'Таласакра'), ('chukalqta', 'Чукалята')], max_length=20),
        ),
    ]
