# Generated by Django 4.1.3 on 2022-12-12 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_giveinformationmodel_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveinformationmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
