# Generated by Django 4.1.3 on 2022-12-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_giveinformationmodel_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giveinformationmodel',
            old_name='created',
            new_name='created_on',
        ),
    ]
