# Generated by Django 4.1.3 on 2022-12-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_giveinformationmodel_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveinformationmodel',
            name='comment',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='giveinformationmodel',
            name='location',
            field=models.CharField(choices=[('Атия', 'Атия'), ('Дюни', 'Дюни'), ('Елените', 'Елените'), ('Емине', 'Емине'), ('Канала', 'Канала'), ('Кокетрайс', 'Кокетрайс'), ('Маслен нос', 'Маслен нос'), ('Мегалката', 'Мегалката'), ('Поморие', 'Поморие'), ('Равда', 'Равда'), ('Созопол', 'Созопол'), ('Ставрова банка', 'Ставрова банка'), ('Таласакра', 'Таласакра'), ('Чукалята', 'Чукалята')], max_length=14),
        ),
    ]
