# Generated by Django 4.1.3 on 2022-12-12 20:43

from django.db import migrations, models
import fishingbs.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_giveinformationmodel_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveinformationmodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='catches/', validators=[fishingbs.accounts.validators.image_max_size_validator]),
        ),
    ]
