# Generated by Django 4.1.3 on 2022-12-12 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_appuser_first_logged'),
        ('news', '0009_alter_giveinformationmodel_from_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveinformationmodel',
            name='from_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
